apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-postgres
spec:
  selector:
    matchLabels:
      app: gallery-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: gallery-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.6-alpine3.21
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: gallery-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: gallery-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gallery-db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["/bin/sh","-c","pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            exec:
              command: ["/bin/sh","-c","pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
